# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pikapsatinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pikpsatinal(object):
    def setupUi(self, pikpsatinal):
        pikpsatinal.setObjectName("pikpsatinal")
        pikpsatinal.resize(663, 616)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        pikpsatinal.setFont(font)
        pikpsatinal.setStyleSheet("background-color:rgb(43,43,43);")
        self.centralwidget = QtWidgets.QWidget(pikpsatinal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lnpikapid = QtWidgets.QLineEdit(self.centralwidget)
        self.lnpikapid.setMaximumSize(QtCore.QSize(200, 200))
        self.lnpikapid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnpikapid.setInputMask("")
        self.lnpikapid.setClearButtonEnabled(True)
        self.lnpikapid.setObjectName("lnpikapid")
        self.verticalLayout.addWidget(self.lnpikapid)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnsat = QtWidgets.QPushButton(self.centralwidget)
        self.btnsat.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnsat.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        self.btnsat.setObjectName("btnsat")
        self.horizontalLayout.addWidget(self.btnsat, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb1_7 = QtWidgets.QLabel(self.centralwidget)
        self.lb1_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.lb1_7.setObjectName("lb1_7")
        self.horizontalLayout_4.addWidget(self.lb1_7)
        self.lnalbumara_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lnalbumara_2.setMaximumSize(QtCore.QSize(200, 200))
        self.lnalbumara_2.setAccessibleName("")
        self.lnalbumara_2.setAccessibleDescription("")
        self.lnalbumara_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnalbumara_2.setClearButtonEnabled(True)
        self.lnalbumara_2.setObjectName("lnalbumara_2")
        self.horizontalLayout_4.addWidget(self.lnalbumara_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.tablo = QtWidgets.QTableWidget(self.centralwidget)
        self.tablo.setStyleSheet("QTableWidget {\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #121212; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3399ff; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #333333; \n"
"    color: #ffffff;\n"
"    padding: 4px;\n"
"    border: 1px solid #444444;\n"
"}")
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(3)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.tablo)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnmenudon = QtWidgets.QPushButton(self.centralwidget)
        self.btnmenudon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnmenudon.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("kedy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnmenudon.setIcon(icon)
        self.btnmenudon.setIconSize(QtCore.QSize(40, 40))
        self.btnmenudon.setObjectName("btnmenudon")
        self.horizontalLayout_2.addWidget(self.btnmenudon)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.btnmenudon_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnmenudon_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnmenudon_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        self.btnmenudon_2.setIcon(icon)
        self.btnmenudon_2.setIconSize(QtCore.QSize(40, 40))
        self.btnmenudon_2.setObjectName("btnmenudon_2")
        self.horizontalLayout_2.addWidget(self.btnmenudon_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(735, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem6)
        pikpsatinal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pikpsatinal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 18))
        self.menubar.setObjectName("menubar")
        pikpsatinal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pikpsatinal)
        self.statusbar.setObjectName("statusbar")
        pikpsatinal.setStatusBar(self.statusbar)

        self.retranslateUi(pikpsatinal)
        QtCore.QMetaObject.connectSlotsByName(pikpsatinal)

    def retranslateUi(self, pikpsatinal):
        _translate = QtCore.QCoreApplication.translate
        pikpsatinal.setWindowTitle(_translate("pikpsatinal", "Plak Satın Al"))
        self.label_3.setText(_translate("pikpsatinal", "Satın alacağınız pikapı seçiniz"))
        self.label_2.setText(_translate("pikpsatinal", "Pikap ID"))
        self.btnsat.setText(_translate("pikpsatinal", "Satın Al"))
        self.lb1_7.setText(_translate("pikpsatinal", "Pikap Adı"))
        self.lnalbumara_2.setPlaceholderText(_translate("pikpsatinal", "Bilgileri Aratınız"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("pikpsatinal", "Plak ID"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("pikpsatinal", "Pikap Adı"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("pikpsatinal", "Plak Fiyatı"))
        self.btnmenudon.setText(_translate("pikpsatinal", "Menüye Geri Dönüş"))
        self.btnmenudon_2.setText(_translate("pikpsatinal", "         Çıkış               "))
