# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plakgor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plakgor(object):
    def setupUi(self, plakgor):
        plakgor.setObjectName("plakgor")
        plakgor.resize(800, 600)
        plakgor.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        plakgor.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.centralwidget = QtWidgets.QWidget(plakgor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tablo = QtWidgets.QTableWidget(self.centralwidget)
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(6)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tablo)
        spacerItem = QtWidgets.QSpacerItem(785, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        plakgor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(plakgor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        plakgor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(plakgor)
        self.statusbar.setObjectName("statusbar")
        plakgor.setStatusBar(self.statusbar)

        self.retranslateUi(plakgor)
        QtCore.QMetaObject.connectSlotsByName(plakgor)

    def retranslateUi(self, plakgor):
        _translate = QtCore.QCoreApplication.translate
        plakgor.setWindowTitle(_translate("plakgor", "Plak Görüntüleme"))
        self.label_2.setText(_translate("plakgor", "Görüntülemek istediğiniz plak bilgilerini giriniz."))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("plakgor", "Plak İd"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("plakgor", "Plak İD"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("plakgor", "Sanatçı"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("plakgor", "Türü"))
        item = self.tablo.horizontalHeaderItem(4)
        item.setText(_translate("plakgor", "Plak Yılı"))
        item = self.tablo.horizontalHeaderItem(5)
        item.setText(_translate("plakgor", "Plak Fiyatı"))
