# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plaksatinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plaksatinal(object):
    def setupUi(self, plaksatinal):
        plaksatinal.setObjectName("plaksatinal")
        plaksatinal.resize(663, 616)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        plaksatinal.setFont(font)
        plaksatinal.setStyleSheet("background-color:rgb(43,43,43);")
        self.centralwidget = QtWidgets.QWidget(plaksatinal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lnplakid = QtWidgets.QLineEdit(self.centralwidget)
        self.lnplakid.setMaximumSize(QtCore.QSize(200, 200))
        self.lnplakid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnplakid.setInputMask("")
        self.lnplakid.setClearButtonEnabled(True)
        self.lnplakid.setObjectName("lnplakid")
        self.verticalLayout.addWidget(self.lnplakid)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnsat = QtWidgets.QPushButton(self.centralwidget)
        self.btnsat.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnsat.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        self.btnsat.setObjectName("btnsat")
        self.horizontalLayout.addWidget(self.btnsat, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb1_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb1_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.lb1_3.setObjectName("lb1_3")
        self.horizontalLayout_3.addWidget(self.lb1_3)
        self.lnalbumara = QtWidgets.QLineEdit(self.centralwidget)
        self.lnalbumara.setMaximumSize(QtCore.QSize(200, 200))
        self.lnalbumara.setAccessibleName("")
        self.lnalbumara.setAccessibleDescription("")
        self.lnalbumara.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnalbumara.setClearButtonEnabled(True)
        self.lnalbumara.setObjectName("lnalbumara")
        self.horizontalLayout_3.addWidget(self.lnalbumara)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tablo = QtWidgets.QTableWidget(self.centralwidget)
        self.tablo.setStyleSheet("QTableWidget {\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #121212; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3399ff; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #333333; \n"
"    color: #ffffff;\n"
"    padding: 4px;\n"
"    border: 1px solid #444444;\n"
"}")
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(6)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tablo)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btndonus = QtWidgets.QPushButton(self.centralwidget)
        self.btndonus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btndonus.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("kedy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btndonus.setIcon(icon)
        self.btndonus.setIconSize(QtCore.QSize(40, 40))
        self.btndonus.setObjectName("btndonus")
        self.horizontalLayout_2.addWidget(self.btndonus)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnmenudon_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnmenudon_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnmenudon_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        self.btnmenudon_2.setIcon(icon)
        self.btnmenudon_2.setIconSize(QtCore.QSize(40, 40))
        self.btnmenudon_2.setObjectName("btnmenudon_2")
        self.horizontalLayout_2.addWidget(self.btnmenudon_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        plaksatinal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(plaksatinal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 18))
        self.menubar.setObjectName("menubar")
        plaksatinal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(plaksatinal)
        self.statusbar.setObjectName("statusbar")
        plaksatinal.setStatusBar(self.statusbar)

        self.retranslateUi(plaksatinal)
        QtCore.QMetaObject.connectSlotsByName(plaksatinal)

    def retranslateUi(self, plaksatinal):
        _translate = QtCore.QCoreApplication.translate
        plaksatinal.setWindowTitle(_translate("plaksatinal", "Plak Satın Al"))
        self.label_3.setText(_translate("plaksatinal", "Satın alma bilgilerini giriniz."))
        self.label_2.setText(_translate("plaksatinal", "Plak ID"))
        self.btnsat.setText(_translate("plaksatinal", "Satın Al"))
        self.lb1_3.setText(_translate("plaksatinal", "Plak Adı"))
        self.lnalbumara.setPlaceholderText(_translate("plaksatinal", "Aratmak istediğiniz bilgiyi giriniz..."))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("plaksatinal", "Plak ID"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("plaksatinal", "Sanatçı"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("plaksatinal", "Albüm Adı"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("plaksatinal", "Türü"))
        item = self.tablo.horizontalHeaderItem(4)
        item.setText(_translate("plaksatinal", "Plak Yılı"))
        item = self.tablo.horizontalHeaderItem(5)
        item.setText(_translate("plaksatinal", "Plak Fiyatı"))
        self.btndonus.setText(_translate("plaksatinal", "Menüye Geri Dönüş"))
        self.btnmenudon_2.setText(_translate("plaksatinal", "         Çıkış               "))
