# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plaksat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plaksat(object):
    def setupUi(self, plaksat):
        plaksat.setObjectName("plaksat")
        plaksat.resize(750, 539)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        plaksat.setFont(font)
        plaksat.setStyleSheet("background-color:rgb(43,43,43);")
        self.centralwidget = QtWidgets.QWidget(plaksat)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb1_5 = QtWidgets.QLabel(self.centralwidget)
        self.lb1_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.lb1_5.setObjectName("lb1_5")
        self.verticalLayout.addWidget(self.lb1_5)
        self.lnpkpmusterid_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lnpkpmusterid_2.setMaximumSize(QtCore.QSize(200, 200))
        self.lnpkpmusterid_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnpkpmusterid_2.setClearButtonEnabled(True)
        self.lnpkpmusterid_2.setObjectName("lnpkpmusterid_2")
        self.verticalLayout.addWidget(self.lnpkpmusterid_2)
        self.lb1_2 = QtWidgets.QLabel(self.centralwidget)
        self.lb1_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.lb1_2.setObjectName("lb1_2")
        self.verticalLayout.addWidget(self.lb1_2)
        self.lnplakad = QtWidgets.QLineEdit(self.centralwidget)
        self.lnplakad.setMaximumSize(QtCore.QSize(200, 200))
        self.lnplakad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnplakad.setClearButtonEnabled(True)
        self.lnplakad.setObjectName("lnplakad")
        self.verticalLayout.addWidget(self.lnplakad)
        self.btnplaksat = QtWidgets.QPushButton(self.centralwidget)
        self.btnplaksat.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnplaksat.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        self.btnplaksat.setObjectName("btnplaksat")
        self.verticalLayout.addWidget(self.btnplaksat)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb1_3 = QtWidgets.QLabel(self.centralwidget)
        self.lb1_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.lb1_3.setObjectName("lb1_3")
        self.verticalLayout_2.addWidget(self.lb1_3)
        self.lnpkpmusterid = QtWidgets.QLineEdit(self.centralwidget)
        self.lnpkpmusterid.setMaximumSize(QtCore.QSize(200, 200))
        self.lnpkpmusterid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnpkpmusterid.setClearButtonEnabled(True)
        self.lnpkpmusterid.setObjectName("lnpkpmusterid")
        self.verticalLayout_2.addWidget(self.lnpkpmusterid)
        self.lb1_4 = QtWidgets.QLabel(self.centralwidget)
        self.lb1_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.lb1_4.setObjectName("lb1_4")
        self.verticalLayout_2.addWidget(self.lb1_4)
        self.lnpikapad = QtWidgets.QLineEdit(self.centralwidget)
        self.lnpikapad.setMaximumSize(QtCore.QSize(200, 200))
        self.lnpikapad.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnpikapad.setClearButtonEnabled(True)
        self.lnpikapad.setObjectName("lnpikapad")
        self.verticalLayout_2.addWidget(self.lnpikapad)
        self.btnplaksat_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnplaksat_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnplaksat_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        self.btnplaksat_2.setObjectName("btnplaksat_2")
        self.verticalLayout_2.addWidget(self.btnplaksat_2, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb1_6 = QtWidgets.QLabel(self.centralwidget)
        self.lb1_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.lb1_6.setObjectName("lb1_6")
        self.horizontalLayout_6.addWidget(self.lb1_6)
        self.lnalbumara = QtWidgets.QLineEdit(self.centralwidget)
        self.lnalbumara.setMaximumSize(QtCore.QSize(200, 200))
        self.lnalbumara.setAccessibleName("")
        self.lnalbumara.setAccessibleDescription("")
        self.lnalbumara.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnalbumara.setClearButtonEnabled(True)
        self.lnalbumara.setObjectName("lnalbumara")
        self.horizontalLayout_6.addWidget(self.lnalbumara)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb1_7 = QtWidgets.QLabel(self.centralwidget)
        self.lb1_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Sans Serif Collection\";")
        self.lb1_7.setObjectName("lb1_7")
        self.horizontalLayout_3.addWidget(self.lb1_7)
        self.lnalbumara_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lnalbumara_2.setMaximumSize(QtCore.QSize(200, 200))
        self.lnalbumara_2.setAccessibleName("")
        self.lnalbumara_2.setAccessibleDescription("")
        self.lnalbumara_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lnalbumara_2.setClearButtonEnabled(True)
        self.lnalbumara_2.setObjectName("lnalbumara_2")
        self.horizontalLayout_3.addWidget(self.lnalbumara_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tablo = QtWidgets.QTableWidget(self.centralwidget)
        self.tablo.setStyleSheet("QTableWidget {\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #121212; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3399ff; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #333333; \n"
"    color: #ffffff;\n"
"    padding: 4px;\n"
"    border: 1px solid #444444;\n"
"}")
        self.tablo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(6)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_4.addWidget(self.tablo)
        self.tablo_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tablo_2.setStyleSheet("QTableWidget {\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #121212; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3399ff; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #333333; \n"
"    color: #ffffff;\n"
"    padding: 4px;\n"
"    border: 1px solid #444444;\n"
"}")
        self.tablo_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tablo_2.setObjectName("tablo_2")
        self.tablo_2.setColumnCount(3)
        self.tablo_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo_2.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_4.addWidget(self.tablo_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnmenudns = QtWidgets.QPushButton(self.centralwidget)
        self.btnmenudns.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnmenudns.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("kedy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnmenudns.setIcon(icon)
        self.btnmenudns.setIconSize(QtCore.QSize(40, 40))
        self.btnmenudns.setObjectName("btnmenudns")
        self.horizontalLayout.addWidget(self.btnmenudns)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.btnmenudon_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnmenudon_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnmenudon_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        self.btnmenudon_2.setIcon(icon)
        self.btnmenudon_2.setIconSize(QtCore.QSize(40, 40))
        self.btnmenudon_2.setObjectName("btnmenudon_2")
        self.horizontalLayout.addWidget(self.btnmenudon_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        plaksat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(plaksat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 18))
        self.menubar.setObjectName("menubar")
        plaksat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(plaksat)
        self.statusbar.setObjectName("statusbar")
        plaksat.setStatusBar(self.statusbar)

        self.retranslateUi(plaksat)
        QtCore.QMetaObject.connectSlotsByName(plaksat)

    def retranslateUi(self, plaksat):
        _translate = QtCore.QCoreApplication.translate
        plaksat.setWindowTitle(_translate("plaksat", "Plak Sat"))
        self.label_3.setText(_translate("plaksat", "Satın alma bilgilerini giriniz."))
        self.lb1_5.setText(_translate("plaksat", "Müsteri İsim-Soyisim"))
        self.lb1_2.setText(_translate("plaksat", "Plak Id"))
        self.btnplaksat.setText(_translate("plaksat", "Sat"))
        self.lb1_3.setText(_translate("plaksat", "Müsteri İsim-Soyisim"))
        self.lb1_4.setText(_translate("plaksat", "Pikap Id"))
        self.btnplaksat_2.setText(_translate("plaksat", "Sat"))
        self.lb1_6.setText(_translate("plaksat", "Plak Adı"))
        self.lnalbumara.setPlaceholderText(_translate("plaksat", "Bilgileri Aratınız"))
        self.lb1_7.setText(_translate("plaksat", "Pikap Adı"))
        self.lnalbumara_2.setPlaceholderText(_translate("plaksat", "Bilgileri Aratınız"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("plaksat", "Plak ID"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("plaksat", "Sanatçı"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("plaksat", "Albüm Adı"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("plaksat", "Türü"))
        item = self.tablo.horizontalHeaderItem(4)
        item.setText(_translate("plaksat", "Plak Yılı"))
        item = self.tablo.horizontalHeaderItem(5)
        item.setText(_translate("plaksat", "Plak Fiyatı"))
        item = self.tablo_2.horizontalHeaderItem(0)
        item.setText(_translate("plaksat", "Plak ID"))
        item = self.tablo_2.horizontalHeaderItem(1)
        item.setText(_translate("plaksat", "Pikap Adı"))
        item = self.tablo_2.horizontalHeaderItem(2)
        item.setText(_translate("plaksat", "Plak Fiyatı"))
        self.btnmenudns.setText(_translate("plaksat", "Menüye Geri Dönüş"))
        self.btnmenudon_2.setText(_translate("plaksat", "         Çıkış               "))
