# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yoneklesil.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_yoneklesil(object):
    def setupUi(self, yoneklesil):
        yoneklesil.setObjectName("yoneklesil")
        yoneklesil.resize(800, 600)
        yoneklesil.setStyleSheet("background-color:rgb(43,43,43);")
        self.centralwidget = QtWidgets.QWidget(yoneklesil)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lyt1 = QtWidgets.QVBoxLayout()
        self.lyt1.setObjectName("lyt1")
        self.lyt2 = QtWidgets.QHBoxLayout()
        self.lyt2.setObjectName("lyt2")
        self.lb1 = QtWidgets.QLabel(self.centralwidget)
        self.lb1.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.lb1.setFont(font)
        self.lb1.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb1.setObjectName("lb1")
        self.lyt2.addWidget(self.lb1)
        self.lb2 = QtWidgets.QLabel(self.centralwidget)
        self.lb2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.lb2.setFont(font)
        self.lb2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb2.setObjectName("lb2")
        self.lyt2.addWidget(self.lb2)
        self.lyt1.addLayout(self.lyt2)
        self.lyt3 = QtWidgets.QHBoxLayout()
        self.lyt3.setObjectName("lyt3")
        self.lyt4 = QtWidgets.QVBoxLayout()
        self.lyt4.setObjectName("lyt4")
        self.lb3 = QtWidgets.QLabel(self.centralwidget)
        self.lb3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        self.lb3.setFont(font)
        self.lb3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb3.setObjectName("lb3")
        self.lyt4.addWidget(self.lb3)
        self.lneklekullan = QtWidgets.QLineEdit(self.centralwidget)
        self.lneklekullan.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lneklekullan.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lneklekullan.setClearButtonEnabled(True)
        self.lneklekullan.setObjectName("lneklekullan")
        self.lyt4.addWidget(self.lneklekullan)
        self.lb4 = QtWidgets.QLabel(self.centralwidget)
        self.lb4.setMaximumSize(QtCore.QSize(16777215, 102))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        self.lb4.setFont(font)
        self.lb4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb4.setObjectName("lb4")
        self.lyt4.addWidget(self.lb4)
        self.lneklesifr = QtWidgets.QLineEdit(self.centralwidget)
        self.lneklesifr.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lneklesifr.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lneklesifr.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lneklesifr.setClearButtonEnabled(True)
        self.lneklesifr.setObjectName("lneklesifr")
        self.lyt4.addWidget(self.lneklesifr)
        self.btnolustur = QtWidgets.QPushButton(self.centralwidget)
        self.btnolustur.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnolustur.setObjectName("btnolustur")
        self.lyt4.addWidget(self.btnolustur, 0, QtCore.Qt.AlignRight)
        self.lyt3.addLayout(self.lyt4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lyt3.addItem(spacerItem)
        self.lyt5 = QtWidgets.QVBoxLayout()
        self.lyt5.setObjectName("lyt5")
        self.lb5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        self.lb5.setFont(font)
        self.lb5.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb5.setObjectName("lb5")
        self.lyt5.addWidget(self.lb5)
        self.lnsilkullan = QtWidgets.QLineEdit(self.centralwidget)
        self.lnsilkullan.setMaximumSize(QtCore.QSize(200, 80))
        self.lnsilkullan.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lnsilkullan.setClearButtonEnabled(True)
        self.lnsilkullan.setObjectName("lnsilkullan")
        self.lyt5.addWidget(self.lnsilkullan)
        self.lb6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        self.lb6.setFont(font)
        self.lb6.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb6.setObjectName("lb6")
        self.lyt5.addWidget(self.lb6)
        self.lnsilsifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lnsilsifre.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lnsilsifre.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.lnsilsifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnsilsifre.setClearButtonEnabled(True)
        self.lnsilsifre.setObjectName("lnsilsifre")
        self.lyt5.addWidget(self.lnsilsifre)
        self.btnsil = QtWidgets.QPushButton(self.centralwidget)
        self.btnsil.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btnsil.setObjectName("btnsil")
        self.lyt5.addWidget(self.btnsil, 0, QtCore.Qt.AlignRight)
        self.lyt3.addLayout(self.lyt5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.lyt3.addItem(spacerItem1)
        self.lyt1.addLayout(self.lyt3)
        self.verticalLayout.addLayout(self.lyt1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.tablo = QtWidgets.QTableWidget(self.centralwidget)
        self.tablo.setStyleSheet("QTableWidget {\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item {\n"
"    background-color: #121212; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3399ff; \n"
"    color: #ffffff; \n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #333333; \n"
"    color: #ffffff;\n"
"    padding: 4px;\n"
"    border: 1px solid #444444;\n"
"}")
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(2)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.tablo)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnmenuyedon = QtWidgets.QPushButton(self.centralwidget)
        self.btnmenuyedon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnmenuyedon.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("kedy.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnmenuyedon.setIcon(icon)
        self.btnmenuyedon.setIconSize(QtCore.QSize(40, 40))
        self.btnmenuyedon.setObjectName("btnmenuyedon")
        self.horizontalLayout_2.addWidget(self.btnmenuyedon)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.CIKKK = QtWidgets.QPushButton(self.centralwidget)
        self.CIKKK.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CIKKK.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Sans Serif Collection\";")
        self.CIKKK.setIcon(icon)
        self.CIKKK.setIconSize(QtCore.QSize(40, 40))
        self.CIKKK.setObjectName("CIKKK")
        self.horizontalLayout_2.addWidget(self.CIKKK)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        yoneklesil.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(yoneklesil)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        yoneklesil.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(yoneklesil)
        self.statusbar.setObjectName("statusbar")
        yoneklesil.setStatusBar(self.statusbar)

        self.retranslateUi(yoneklesil)
        QtCore.QMetaObject.connectSlotsByName(yoneklesil)

    def retranslateUi(self, yoneklesil):
        _translate = QtCore.QCoreApplication.translate
        yoneklesil.setWindowTitle(_translate("yoneklesil", "Yönetici Ekle/Sil"))
        yoneklesil.setAccessibleName(_translate("yoneklesil", "Ekle/sil"))
        self.lb1.setText(_translate("yoneklesil", "Eklemek istediğiniz yönetici için bilgileri giriniz."))
        self.lb2.setText(_translate("yoneklesil", "Silmek istediğiniz yönetici için bilgileri giriniz."))
        self.lb3.setText(_translate("yoneklesil", "Kullanıcı Adı:"))
        self.lb4.setText(_translate("yoneklesil", "Şifre:"))
        self.btnolustur.setText(_translate("yoneklesil", "Oluştur"))
        self.lb5.setText(_translate("yoneklesil", "Kullanıcı Adı:"))
        self.lb6.setText(_translate("yoneklesil", "Şifre:"))
        self.btnsil.setText(_translate("yoneklesil", "Sil"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("yoneklesil", "Kullanıcı Adı"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("yoneklesil", "Şifre"))
        self.btnmenuyedon.setText(_translate("yoneklesil", "Menüye Geri Dönüş"))
        self.CIKKK.setText(_translate("yoneklesil", "             Çıkış           "))
